export const ErrorCodeEnum = {
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
